<a href="https://colab.research.google.com/github/xqyn/deep-learning/blob/main/6.874/tensor-flow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy

In [2]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.9.2


In [ ]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [ ]:
# Create a Tensor.
hello = tf.constant("hello world")
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [3]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 [==============================] - 0s 0us/step


In [4]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [5]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.19990475,  0.1965591 ,  0.34891146,  0.6175257 ,  0.26486108,
        -0.13579977,  0.05527702, -0.0110431 , -0.4273323 , -0.5297179 ]],
      dtype=float32)

In [6]:
tf.nn.softmax(predictions).numpy()

array([[0.07601968, 0.11300772, 0.13160546, 0.17215973, 0.12099608,
        0.08105251, 0.09811831, 0.09182218, 0.06055577, 0.05466257]],
      dtype=float32)

In [7]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [8]:
loss_fn(y_train[:1], predictions).numpy()

2.512658

In [11]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [12]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.1073 - accuracy: 0.9678
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0858 - accuracy: 0.9736
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0721 - accuracy: 0.9771
Epoch 4/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0649 - accuracy: 0.9795
Epoch 5/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.0585 - accuracy: 0.9811


In [13]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0718 - accuracy: 0.9798 - 736ms/epoch - 2ms/step


[0.0717720314860344, 0.9797999858856201]

In [14]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [15]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[2.5926339e-10, 1.3364304e-10, 2.5640004e-08, 1.3427788e-06,
        3.5476928e-14, 5.0981075e-10, 1.6006517e-17, 9.9999869e-01,
        1.6442876e-08, 2.2942118e-08],
       [1.8887296e-09, 1.8160274e-05, 9.9998176e-01, 7.2784729e-08,
        5.0179979e-21, 5.1767774e-08, 1.2214224e-09, 1.7676975e-12,
        4.1847247e-08, 5.7950635e-19],
       [8.8548248e-08, 9.9951100e-01, 6.9738322e-05, 1.7454502e-06,
        1.1953466e-06, 3.1427288e-07, 1.7437197e-06, 3.6251673e-04,
        5.1631247e-05, 1.3662160e-08],
       [9.9964392e-01, 6.7004624e-11, 6.0850398e-06, 6.5236909e-09,
        6.5489282e-08, 2.0371864e-07, 1.6034276e-06, 3.2502701e-04,
        7.5227102e-10, 2.2962246e-05],
       [2.0477428e-08, 8.3561786e-12, 3.3997271e-06, 6.1777086e-09,
        9.9909878e-01, 2.2041673e-09, 2.4880692e-06, 2.2561086e-05,
        1.7802927e-06, 8.7106915e-04]], dtype=float32)>

#Video tutorials

In [17]:
import keras

In [23]:
import numpy as np

In [19]:
model = keras.Sequential([keras.layers.Dense(units=1,input_shape=[1])])

In [27]:
model.compile(optimizer='sgd',loss='mean_squared_error')

In [24]:
xs=np.array([-1,0,1,2,3,4], dtype=float)

In [34]:
ys=np.array([-3,-1,1,3,5,7], dtype=float)

In [35]:
%%capture
model.fit(xs,ys,epochs=500)

In [36]:
print(model.predict([10.0]))

1/1 [==============================] - 0s 30ms/step
[[18.998941]]


## Basic Computer Vision with ML (ML Zero to Hero - Part 2)

In [38]:
import tensorflow as tf
from tensorflow import keras

In [39]:
fashion_mnist = keras.datasets.fashion_mnist

In [56]:
(train_images,train_labels),(test_images,test_labels) = fashion_mnist.load_data()

In [50]:
model = keras.Sequential([
    keras.layers.Flatten(input_shape=(28,28)),
    keras.layers.Dense(128, activation=tf.nn.relu),
    keras.layers.Dense(10, activation=tf.nn.softmax)
    ])

In [69]:
#model.compile(optimizer = tf.train.AdamOptimizer(),
#              loss='sparse_categirical_crossentropy')
model.compile(optimizer = tf.keras.optimizers.Adam(),
              loss = 'sparse_categorical_crossentropy',
              metrics='accuracy')

In [71]:
model.fit(train_images,train_labels,epochs=5)

Epoch 1/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.5881 - accuracy: 0.7610
Epoch 2/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.5735 - accuracy: 0.7668
Epoch 3/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.5727 - accuracy: 0.7658
Epoch 4/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.5635 - accuracy: 0.7709
Epoch 5/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.5629 - accuracy: 0.7767


In [62]:
model

In [72]:
test_loss, test_acc = model.evaluate(test_images,test_labels)

313/313 [==============================] - 1s 2ms/step - loss: 0.6334 - accuracy: 0.7669


In [73]:
predictions = model.predict(my_images)

NameError: ignored